<?php 
require("../inc/fonction.php");
    if(!verify_user($_GET['mail'],$_GET['motdepasse'])){
        header("Location:login.php?erreur=1");
    }
    else{
        $user=get_info_member($_GET['mail'],$_GET['motdepasse']);
        $_SESSION['utilisateur']=$user['nom'];
        $_SESSION['id']=$user['id_membre'];
        header("Location:accueil.php");
    }
?>